#!/usr/bin/env bash
# Frontend on localhost:5000 with Poornasree API on the VPS (not local api/).
#
# Usage (from repo root):
#   ./scripts/dev-with-server-api.sh              # SSH tunnel → server API :4002
#   ./scripts/dev-with-server-api.sh --public     # HTTPS ai.poornasreecloud.com (no tunnel)
#
# Env overrides:
#   SSH_HOST=poornasree-v4   REMOTE_API_PORT=4002   LOCAL_API_PORT=4002   LOCAL_WEB_PORT=5000
#   API_INTERNAL_URL=...     skip tunnel/public and use this URL directly

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

SSH_HOST="${SSH_HOST:-${DEPLOY_SSH_HOST:-poornasree-v4}}"
REMOTE_API_PORT="${REMOTE_API_PORT:-4002}"
LOCAL_API_PORT="${LOCAL_API_PORT:-4002}"
LOCAL_WEB_PORT="${LOCAL_WEB_PORT:-5000}"
PUBLIC_API_BASE="${PUBLIC_API_BASE:-https://ai.poornasreecloud.com}"

USE_PUBLIC=0
if [[ "${1:-}" == "--public" ]]; then
  USE_PUBLIC=1
  shift
fi
if [[ $# -gt 0 ]]; then
  echo "Unknown arg: $*"
  echo "Usage: $0 [--public]"
  exit 1
fi

api_health_ok() {
  local base="$1"
  local code
  code="$(curl -sS -o /dev/null -w "%{http_code}" --connect-timeout 3 "${base}/health" 2>/dev/null || echo "000")"
  [[ "$code" == "200" ]]
}

echo "🚀 PoornasreeAI dev: local web + server API"
echo ""

if [[ -n "${API_INTERNAL_URL:-}" ]]; then
  TARGET_API="$API_INTERNAL_URL"
  echo "📝 Using API_INTERNAL_URL from environment: $TARGET_API"
elif [[ "$USE_PUBLIC" -eq 1 ]]; then
  TARGET_API="$PUBLIC_API_BASE"
  echo "📝 Using public API (no SSH tunnel): $TARGET_API"
else
  TARGET_API="http://127.0.0.1:${LOCAL_API_PORT}"
  echo "📝 API via SSH tunnel: ${TARGET_API} → ${SSH_HOST}:127.0.0.1:${REMOTE_API_PORT}"
fi
echo ""

if [[ -z "${API_INTERNAL_URL:-}" ]] && [[ "$USE_PUBLIC" -eq 0 ]]; then
  if api_health_ok "$TARGET_API"; then
    echo "✅ Server API already reachable at $TARGET_API"
  else
    echo "🔗 Opening SSH tunnel (background)..."
    if ! ssh -o BatchMode=yes -o ConnectTimeout=12 -f -N \
      -L "${LOCAL_API_PORT}:127.0.0.1:${REMOTE_API_PORT}" \
      "$SSH_HOST" 2>/dev/null; then
      echo "❌ SSH tunnel failed. Try: ssh $SSH_HOST"
      echo "   Or use: $0 --public"
      exit 1
    fi
    for _ in $(seq 1 30); do
      if api_health_ok "$TARGET_API"; then
        echo "✅ Server API is up at $TARGET_API"
        break
      fi
      sleep 0.5
    done
    if ! api_health_ok "$TARGET_API"; then
      echo "❌ API not healthy at ${TARGET_API}/health"
      echo "   On the server, check: curl -s http://127.0.0.1:${REMOTE_API_PORT}/health"
      exit 1
    fi
  fi
elif [[ "$USE_PUBLIC" -eq 1 ]] || [[ -n "${API_INTERNAL_URL:-}" ]]; then
  if ! api_health_ok "$TARGET_API"; then
    code="$(curl -sS -o /dev/null -w "%{http_code}" --connect-timeout 5 "${TARGET_API}/health" 2>/dev/null || echo "000")"
    echo "⚠️  GET ${TARGET_API}/health returned HTTP ${code} (continuing anyway)"
  else
    echo "✅ API health OK at $TARGET_API"
  fi
fi
echo ""

echo "📝 Writing .env.local (API_INTERNAL_URL)..."
cat > "$REPO_ROOT/.env.local" << EOF
# Generated by scripts/dev-with-server-api.sh — safe to edit; re-run script to reset.
API_INTERNAL_URL=${TARGET_API}
EOF
echo "✅ API_INTERNAL_URL=${TARGET_API}"
echo ""

if [[ ! -d node_modules ]]; then
  echo "📦 Installing frontend dependencies..."
  npm install
  echo ""
fi

if lsof -ti:"$LOCAL_WEB_PORT" >/dev/null 2>&1; then
  echo "⚠️  Port $LOCAL_WEB_PORT is in use — stop that process or set LOCAL_WEB_PORT."
  exit 1
fi

echo "🌐 Starting Next.js on http://localhost:${LOCAL_WEB_PORT}"
echo "   /api/* and /socket.io proxy to the server API."
echo "   Press Ctrl+C to stop the web server (SSH tunnel may keep running)."
echo ""

exec npx next dev -p "$LOCAL_WEB_PORT"
